// app.js
let priceChart; 
let globalData = {};
let currentCardId = null;
let currentRange = 'all';
let currentLang = 'en';

let frontendConfig = [];

const translations = {
    en: {
        title: "ポケtracker",
        searchbox: "Search name or number...",
        tracked: "Tracked Variants",
        live: "Market Data Live",
        source: "Source: SNKRDUNK / PPT",
        select: "Select a Card",
        subtitle: "Detailed market history & trends",
        latest_price: "Latest Price (JPY)",
        all_time: "All Time",
        monthly: "30 Days",
        weekly: "7 Days"
    },
    ja: {
        title: "ポケtracker",
        searchbox: "名前やカード番号で検索...",
        tracked: "トラッキング中",
        live: "マーケットデータ稼働中",
        source: "ソース: SNKRDUNK / PPT",
        select: "カードを選択",
        subtitle: "詳細な市場履歴とトレンド",
        latest_price: "最新価格 (JPY)",
        all_time: "全期間",
        monthly: "30日間",
        weekly: "7日間"
    }
};

async function init() {
    setupTimeButtons();
    setupSearch();
    
    document.getElementById('lang-toggle').addEventListener('click', toggleLang);
    
    try {
        const response = await fetch('data/prices.json');
        globalData = await response.json();
        
        // Build frontend config purely from the heavy data structure generated by the backend
        frontendConfig = Object.keys(globalData).map(key => {
            const meta = globalData[key].metadata || {};
            return {
                id: key,
                name: meta.name_en || key,
                name_ja: meta.name_ja || '',
                number: meta.number || '???',
                condition: meta.condition || 'Raw',
                imageUrl: meta.imageUrl || ''
            };
        });

        renderSidebar();
        
        if (frontendConfig.length > 0) {
            selectCard(frontendConfig[0].id);
        }
        // Initialize explicit EN text state based on translations object
        setLanguageDOM();
    } catch (e) {
        console.error("Failed to load price data", e);
        document.getElementById('selected-card-name').innerText = "Data Load Error";
    }
}

function toggleLang() {
    currentLang = currentLang === 'en' ? 'ja' : 'en';
    document.getElementById('lang-toggle').innerText = currentLang === 'en' ? 'JP / EN' : 'EN / JP';
    
    setLanguageDOM();
    renderSidebar(document.getElementById('card-search').value);
    if (currentCardId) selectCard(currentCardId);
}

function setLanguageDOM() {
    document.querySelectorAll('[data-i18n]').forEach(el => {
        const key = el.getAttribute('data-i18n');
        if (translations[currentLang][key]) {
            if (el.tagName === 'INPUT' && el.type === 'text') {
                el.placeholder = translations[currentLang][key];
            } else {
                el.innerText = translations[currentLang][key];
            }
        }
    });
}

function setupSearch() {
    document.getElementById('card-search').addEventListener('input', (e) => {
        renderSidebar(e.target.value);
    });
}

function renderSidebar(filterText = '') {
    const ul = document.getElementById('card-list');
    ul.innerHTML = '';
    
    // Filter logic
    const lowerFilter = filterText.toLowerCase();
    const filteredCards = frontendConfig.filter(c => {
        const matchName = c.name.toLowerCase().includes(lowerFilter);
        const matchNameJa = c.name_ja && c.name_ja.toLowerCase().includes(lowerFilter);
        const matchNumber = c.number.toLowerCase().includes(lowerFilter);
        return matchName || matchNameJa || matchNumber;
    });
    
    filteredCards.forEach(card => {
        const li = document.createElement('li');
        li.className = 'list-item';
        // Keeps selection styling correctly
        if (card.id === currentCardId) li.classList.add('active');
        li.dataset.id = card.id;
        
        const nameText = currentLang === 'ja' && card.name_ja ? card.name_ja : card.name;
        
        li.innerHTML = `
            <div style="display:flex; flex-direction:column; gap:4px; max-width:160px;">
                <span style="white-space: nowrap; overflow: hidden; text-overflow: ellipsis; font-size:13px;">${nameText}</span>
                <span style="font-size: 11px; color: var(--text-secondary);">${card.number}</span>
            </div>
            <small>${card.condition}</small>`;
        
        li.addEventListener('click', () => selectCard(card.id));
        ul.appendChild(li);
    });
}

function selectCard(id) {
    currentCardId = id;

    // UI Sidebar Selection
    document.querySelectorAll('.list-item').forEach(el => el.classList.remove('active'));
    document.querySelector(`.list-item[data-id="${id}"]`)?.classList.add('active');

    const cardInfo = frontendConfig.find(c => c.id === id);
    if (!cardInfo) return;

    // Text info
    const nameText = currentLang === 'ja' && cardInfo.name_ja ? cardInfo.name_ja : cardInfo.name;
    document.getElementById('selected-card-name').innerText = `${nameText} (${cardInfo.condition})`;
    document.getElementById('selected-card-meta').innerText = `Variant: ${cardInfo.number} | ID: ${id}`;

    // Image preview
    const imgEl = document.getElementById('card-image');
    if (cardInfo.imageUrl) {
        imgEl.src = cardInfo.imageUrl;
        imgEl.classList.remove('hidden');
    } else {
        imgEl.classList.add('hidden');
    }

    refreshChartData();
}

function setupTimeButtons() {
    document.querySelectorAll('.time-btn').forEach(btn => {
        btn.addEventListener('click', (e) => {
            // Update active state
            document.querySelectorAll('.time-btn').forEach(b => b.classList.remove('active'));
            e.target.classList.add('active');
            
            // Set range and re-render chart
            currentRange = e.target.dataset.range;
            refreshChartData();
        });
    });
}

function refreshChartData() {
    if (!currentCardId) return;

    const fullRecord = globalData[currentCardId] || { history: [] };
    let dataPoints = fullRecord.history;

    // Filter by timeline
    if (currentRange !== 'all') {
        const now = new Date();
        const daysToSubtract = currentRange === 'weekly' ? 7 : 30;
        const cutoffDate = new Date(now.setDate(now.getDate() - daysToSubtract));
        
        dataPoints = dataPoints.filter(dp => new Date(dp.date) >= cutoffDate);
    }

    // Update Latest Price display
    const isRaw = frontendConfig.find(c => c.id === currentCardId)?.condition === 'Raw';
    if (dataPoints.length > 0) {
        if (isRaw) {
            const latest = [...dataPoints].reverse().find(dp => dp.cardrush_jpy !== null);
            document.getElementById('latest-price-jpy').innerText = latest ? `¥${latest.cardrush_jpy.toLocaleString()}` : "N/A";
        } else {
            const latest = [...dataPoints].reverse().find(dp => dp.snkrdunk_jpy !== null);
            document.getElementById('latest-price-jpy').innerText = latest ? `¥${latest.snkrdunk_jpy.toLocaleString()}` : "N/A";
        }
    } else {
        document.getElementById('latest-price-jpy').innerText = "No Data";
    }

    renderChart(dataPoints);
}

function renderChart(dataPoints) {
    const ctx = document.getElementById('priceChart').getContext('2d');
    
    const isDarkMode = window.matchMedia && window.matchMedia('(prefers-color-scheme: dark)').matches;
    const gridColor = isDarkMode ? 'rgba(255, 255, 255, 0.1)' : 'rgba(0, 0, 0, 0.1)';
    const textColor = isDarkMode ? '#a1a1a6' : '#86868b';

    const isRaw = frontendConfig.find(c => c.id === currentCardId)?.condition === 'Raw';
    const chartLabel = isRaw ? 'Card Rush (¥)' : 'SNKRDUNK (¥)';
    
    const labels = dataPoints.map(dp => dp.date);
    const plotData = isRaw ? dataPoints.map(dp => dp.cardrush_jpy) : dataPoints.map(dp => dp.snkrdunk_jpy);

    if (priceChart) {
        priceChart.destroy();
    }

    priceChart = new Chart(ctx, {
        type: 'line',
        data: {
            labels: labels,
            datasets: [
                {
                    label: chartLabel,
                    data: plotData,
                    borderColor: '#007aff',
                    backgroundColor: 'rgba(0, 122, 255, 0.1)',
                    borderWidth: 2,
                    pointBackgroundColor: '#007aff',
                    pointRadius: 4,
                    pointHoverRadius: 6,
                    fill: true,
                    tension: 0.4
                }
            ]
        },
        options: {
            responsive: true,
            maintainAspectRatio: false,
            plugins: {
                legend: { display: false },
                tooltip: {
                    mode: 'index',
                    intersect: false,
                    backgroundColor: isDarkMode ? 'rgba(30, 30, 30, 0.9)' : 'rgba(255, 255, 255, 0.9)',
                    titleColor: isDarkMode ? '#fff' : '#000',
                    bodyColor: isDarkMode ? '#fff' : '#000',
                    borderColor: isDarkMode ? 'rgba(255,255,255,0.2)' : 'rgba(0,0,0,0.1)',
                    borderWidth: 1
                }
            },
            scales: {
                x: {
                    grid: { color: gridColor, drawBorder: false },
                    ticks: { color: textColor }
                },
                y: {
                    grid: { color: gridColor, drawBorder: false },
                    ticks: {
                        color: textColor,
                        callback: function(value) { return '¥' + value.toLocaleString(); }
                    }
                }
            },
            interaction: { mode: 'nearest', axis: 'x', intersect: false }
        }
    });
}

document.addEventListener('DOMContentLoaded', init);
